### ISSUE TITLE
Failing when ovirt_engine_setup_use_remote_answer_file is not defined

### ISSUE THREAD

**Issue by petr-balogh** [oVirt/ovirt-ansible-engine-setup#19]
I see our automation is failing cause of this variable is not defined.

Error: 
18:57:41 fatal: [jenkins-vm-03.lab.eng.tlv2.redhat.com]: FAILED! => {"msg": "The conditional check 'ovirt_engine_setup_use_remote_answer_file' failed. The error was: error while evaluating conditional (ovirt_engine_setup_use_remote_answer_file): 'ovirt_engine_setup_use_remote_answer_file' is undefined\n\nThe error appears to have been in '/var/lib/jenkins/workspace/rhv-ge-deploy-4.2@2/ansible-roles-deps/oVirt.engine-setup/tasks/engine_setup.yml': line 25, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Use remote's answer file\n    ^ here\n"}

I think that it should be fixed by some default value.

**Comment by petr-balogh** [comment]
I am PTO till 9.9. I did just small WA in our repo to pass this variable. But I think it deserve proper fix here.  Maybe task for Jiri Macku, our new colleague ;) He will probably contact you tomorrow and hope he will propose the fix here. Cheers, Petr

**Comment by machacekondra** [comment]
Please try with: https://github.com/oVirt/ovirt-ansible-engine-setup/pull/20

**Comment by jirimacku** [comment]
I think we should also test the variable first (#21 )

**Comment by mwperina** [comment]
> I think we should also test the variable first (#21 )

Why do we need the test, when we have the default value set to False?
