### ISSUE TITLE
integrate fast forward upgrade mechanism to role

### ISSUE THREAD

**Issue by mgoldboi** [oVirt/ovirt-ansible-engine-setup#36]
please explore the option to integrated FF upgrade (https://github.com/oVirt/ovirt-fast-forward-upgrade) to the engine-setup (upgrade) role.

**Comment by machacekondra** [comment]
@mnecas

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
