### ISSUE TITLE
aaa-ldap integration

### ISSUE THREAD

**Issue by Klaas-** [oVirt/ovirt-ansible-engine-setup#53]
Hi,
would you consider this role to be the right place for ldap or general auth configuration? I am currently thinking about implementing this and I am not sure if I should extend this role or create a "post install engine" role

Greetings
Klaas

**Comment by djasa** [comment]
Hi @Klaas-, there is a role for that by @machacekondra: https://github.com/machacekondra/ansible-role-ovirt-aaa-ldap .

**Comment by mwperina** [comment]
Development moved to https://github.com/ovirt/ovirt-ansible-collection If this is still relevant, please reopen there.
