### ISSUE TITLE
ovirt_engine_setup_offline and ovirt_engine_setup_update_all_packages discrepancy

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-ansible-engine-setup#74]
I suggest to squash these into just a single option. You either want to update everything ro run in offline environment.
But having e.g. ovirt_engine_setup_update_all_packages=true and ovirt_engine_setup_offline=true doesn't make sense - you update all the packages and then setup fails because it's not allowed to install matching packages (in versionlock). Similarly the other way around.

It makes sense to only have a single option and derive a correct --offline parameter from it

**Comment by sandrobonazzola** [comment]
@mnecas , @mwperina can you please have a look?

**Comment by mnecas** [comment]
I would rather update the logic so it prioritize one thing over the other instead of squashing both parameters to one. 
I think there could become situation where both would be False and if we would have only one parameter which would switch between update and offline we would loose that. 
What do you think @michalskrivanek ?

**Comment by michalskrivanek** [comment]
false as in "engien setup would try update" but you won't update packages prior to that?
It's fine either way, just pointing out that true/true and false/false do not make sense and likely doesn't really work properly during deployment

**Comment by mnecas** [comment]
after doing more investigation I would also rather use only one parameter but don't want to break any backport compatibility

**Comment by michalskrivanek** [comment]
@mnecas up to you. I guess not an issue to introduce a new one and deprecate the other two, or just keep it as is and clarify in documentation.
