### ISSUE TITLE
Playbook fail with "Python 2 yum module is needed for this module"

### ISSUE THREAD

**Issue by allangood** [oVirt/ovirt-ansible-engine-setup#89]
Hi,

When I try to deploy the hosted_engine I always get this error:

```
[ INFO  ] TASK [ovirt.hosted_engine_setup : Install oVirt Hosted Engine packages]
[ ERROR ] fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
[ ERROR ] Failed to execute stage 'Closing up': Failed executing ansible-playbook
[ INFO  ] Stage: Clean up
```

I'm using ovirt node 4.4.11

Let me know if more information is needed.

Regards.

**Comment by mwperina** [comment]
This role is used only for standalone engine installation, it cannot be used for hosted engine installation.

The issue you have described is already being tracked by https://bugzilla.redhat.com/1858234
